version: 2

sources:
  - name: economic_data 
    database: etl-economic-indicators #Project_id 
    schema: economic_data # Name of Dataset
    tables:
      - name: economic_indicators 
      - name: dates
      - name: countries 
      - name: indicators 